### ISSUE TITLE
Error in test statement

### ISSUE THREAD

**Issue by lmburns** [sayanarijit/zoxide.xplr#1]
```
if [ "$PTH" ]; then...
```

```
Needs to be changed to 
if [ -d "$PTH" ]; then...
```

Replying to your comment from yesterday, yes I could maintain and develop some of these plugins.

Also, it seems that after this new update, whenever I call anything having to do with `fzf` it has become way slower. Is there a reason for this or something I need to change from the functions I had submitted a couple of weeks ago?

**Comment by sayanarijit** [comment]
> Replying to your comment from yesterday, yes I could maintain and develop some of these plugins.

Great!. Let me know which plugins you'd like to maintain. We can continue on [discord](https://discord.gg/JmasSPCcz3) or [keybase](https://keybase.io/sayanarijit).

> Also, it seems that after this new update, whenever I call anything having to do with fzf it has become way slower. Is there a reason for this or something I need to change from the functions I had submitted a couple of weeks ago?

Not sure... mine runs fine. Does running `fzf` standalone cause any slowness?
